### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by zeeev** [38/HTSLibXX#2]
Hi @38,

Thank you very much for writing this interface. I was wondering if you could provide some very basic code examples? Like how to replace bamtools headers with this code, and or an example of how to open and read a cram? Maybe a quick cheat sheet or something? I'm about to refactor a large codebase to use HTSLibXX and would appreciate a few little hints.

Best,

Zev

**Comment by 38** [comment]
Hi Zev,

Thank you for asking. This lib is designed as an adapt layer between htslib and application based on BamTools. 
The only thing should be done is 1) Replace bamtools headers with this repo 2) Link your binary with htslib. For most of the case, C++ compiler knows what code to generate by implicit conversion. In some case, you probably need a explicit cast to make it compile (but very rare).

In fact, I am using a modified version of htslib, because some performance consideration. 
https://github.com/38/htslib 
The difference is 1) Remove checksum code for performance 2) Add placement initialization for a bam_t type for memory access efficiency.

The use of the library is almost identical to bamtools.

```C++
BamReader br;
br.Open("your/bam/file");
BamAlignment read;
while(br.GetNextAligment(read)) { 
.....
}
br.Close();
```

The cram support is roughly the same, because htslib provides identical interface for both CRAM and BAM.

But this library isn't fully functioning and may need some further development. And it's used to integrate htslib to bedtools. You can see the change at https://github.com/arq5x/bedtools2/pull/620


Hope this is helpful,
Hao

**Comment by 38** [comment]
Just created an example of basic usage of the lib.

https://github.com/38/HTSLibXX/tree/master/example

Hope this is helpful to you.

**Comment by zeeev** [comment]
This is great! Thanks.
